### ISSUE TITLE
Implement onboarding landing page

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#11]
Implement the onboarding landing page as a fragment in the Onboarding Activity.

Please define related colors and text & button styles in the corresponding values files.

Some basic scaffolding was added, but it needs to be cleaned up. 

![image](https://user-images.githubusercontent.com/1358055/113337193-1d0c7100-9330-11eb-81c8-a89a7dad0602.png)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by toaderandrei** [comment]
I will take care of the #11 #12 for now. If I can maybe the rest as well(#13  and #14). First #11 and #12 and then we can sync.
