### ISSUE TITLE
Implement onboarding address type picker fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#12]
Implement the address type picker fragment in the Onboarding Activity.

Please define related colors and text & button styles in the corresponding values files.

Some basic scaffolding was added, but it needs to be cleaned up. 

the types should be retrieved from the backend. endpoint to be decided. https://github.com/code4romania/de-urgenta-backend/issues/51

![image](https://user-images.githubusercontent.com/1358055/113339925-e2a4d300-9333-11eb-88d5-df9e02e3b2eb.png)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by aniri** [comment]
assigned to toaderandrei

**Comment by toaderandrei** [comment]
I will take care of that as most of the map fragments are related.

**Comment by toaderandrei** [comment]
As I did not push in the previous PR, I will open another to fix this separately. I created a PR not to have many changes at once.

**Comment by aniri** [comment]
This should be integrated as seamlessly as possible in the existing address related fragments. They can be reorganized as needed and reused.

**Comment by aniri** [comment]
closing this as is was mostly implemented :D
