### ISSUE TITLE
Implement add new address flow fragments

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#13]
Implement the add address flow as reusable fragments.

Use them in the Onboarding Activity:
- the first time the user selects the option to add a new address, the flow should start with the address type set to home
- after adding the new address, the screen with the list of added addresses should be displayed with the option to add another address
- the following time the user chooses to add a new address, the address type picker should be displayed first ( depends on https://github.com/code4romania/de-urgenta-android/issues/12 )

The addresses should also be stored locally after the success response from the backend.

In case there is no internet connection when the user tries to save the address, an error should be displayed ( depends on https://github.com/code4romania/de-urgenta-android/issues/8 )

Please define related colors and text & button styles in the corresponding values files.

Some basic scaffolding was added, but it needs to be cleaned up. 

Map provider: here maps
to be added: save address endpoint

![image](https://user-images.githubusercontent.com/1358055/113340152-31eb0380-9334-11eb-9a19-f8d44acecd0f.png)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by toaderandrei** [comment]
I did everything but the last part as saving api call - at least my understanding was not done yet.

**Comment by aniri** [comment]
closing this as it was implemented. will open separate issue for integration with api
