### ISSUE TITLE
Setup for main activity navigation menu

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#16]
Design main menu and setup for navigation between the main activity fragments.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113397672-18829f80-93a6-11eb-9fa6-c0c8796d17af.png)

Please use navigation drawer and material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by andreea-sicaru** [comment]
I'll take the layout for this one.
