### ISSUE TITLE
Design home screen

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#17]
Design home screen for main activity.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113398002-9777d800-93a6-11eb-9fd3-daf238832d6a.png)

Please use navigation drawer and material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by andreea-sicaru** [comment]
I'll start this.
