### ISSUE TITLE
Implement layout for backpack fragments

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#24]
Design main backpack fragments.

Please define related colors and text & button styles in the corresponding values files.

Clicking on the `rucsacul meu` option, should take the user to the next fragment. Clicking on `aminteste-mi ...`should take the user back to the home screen.

Add an enum for the backpack categories, as the category id should be sent to the backend when saving a new backpack item. These are:
```
1 - apă și alimente
2 - articole de igienă
3 - trusă de prim ajutor
4 - documente
5 - articole de supraviețuire
6 - diverse
```

![image](https://user-images.githubusercontent.com/1358055/113514827-74515200-9579-11eb-8076-e9d6d2b8938b.png)

Please use material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :) For example, the title should be placed in the action bar with a back button instead of the X.

[Link to API in swagger](https://api.deurgenta.hostmysite.ro/swagger/index.html)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by lukstbit** [comment]
If it isn't already taken, I'll work on this issue along with #25 and #26

**Comment by aniri** [comment]
closing this as layout was implemented
