### ISSUE TITLE
Implement layout for about screen

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#33]
Design about app fragment.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113607171-94544480-9651-11eb-83e6-626f79021198.png)

Please use material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :) For example, the title should be placed in the action bar with a back button instead of the X.

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by andreea-sicaru** [comment]
I'll implement this UI.

**Comment by andreea-sicaru** [comment]
Hey, sorry but I can't work on this anymore 😞

**Comment by aniri** [comment]
closing this as it was implemented in #44
