### ISSUE TITLE
Integrate register endpoint

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#38]
The register endpoint was implemented in the backend https://api.deurgenta.hostmysite.ro/swagger/index.html

Please add it in the app, the layout for the register page is already implemented.

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by GabrielMajeri** [comment]
@aniri I would like to work on this!

I've looked at the Swagger API, and the bit that confuses me is the email confirmation feature. After calling `/api/register`, the back end sends a confirmation email to the user.

Do we need to allow them to input this code in the app, or do we just redirect them to the login page after they register?

**Comment by aniri** [comment]
@GabrielMajeri hey :D we should just redirect them to the login page for now :D no need to complicate the flow. the confirmation email has no code or anything in it ;)

**Comment by aniri** [comment]
depends on https://github.com/code4romania/de-urgenta-backend/issues/56

**Comment by aniri** [comment]
@GabrielMajeri the backend issue was implemented ;)

**Comment by GabrielMajeri** [comment]
@aniri yes, but unfortunately, it currently crashes when calling the register endpoint 🙁 I've left a comment there describing the issue.
