### ISSUE TITLE
Implement login landing page

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#4]
Implement the login landing page as a fragment in the Login Activity.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113330518-7de37b80-9327-11eb-95fc-54a49d85351f.png)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by ClaudiuBogdan** [comment]
🙋 I can take charge of this issue.

**Comment by ClaudiuBogdan** [comment]
Figma has a different design than the image of this issue. Which one must be implemented?

**Comment by aniri** [comment]
> Figma has a different design than the image of this issue. Which one must be implemented?

@ClaudiuBogdan figma is the source of truth since small updates are still being made. but, for now, the design from the screenshot above should be enough until we implement the routes feature :) so if you already implemented the one in the screenshot, that's perfect :)

**Comment by aniri** [comment]
closing this one as it was implemented
