### ISSUE TITLE
Implement add group fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#41]
Design add group fragment. 

Prepare setup for api call and ui navigation between fragments.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/115766115-3ee99880-a3b0-11eb-9f9d-f2b1d1167ebb.png)

Please use material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :) For example, the title should be placed in the action bar with a back button instead of the X.

[Link to API in swagger](https://api.deurgenta.hostmysite.ro/swagger/index.html)

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by GabrielMajeri** [comment]
I want to work on this 🙋‍♂️

Should I make this fragment inherit from `ViewModelFragment` with an appropriate view model, or from `DialogFragment`?

**Comment by aniri** [comment]
@GabrielMajeri it should inherit from `ViewModelFragment` , the fragments setup should be similar to https://github.com/code4romania/de-urgenta-android/pull/35/files
