### ISSUE TITLE
Implement main settings fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#42]
Design settings fragment.

Selecting the `Raporteaza o problema` option should open the email app to compose a new email. The `to` address should be pre-filled with a value stored in the properties files.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/115766576-cdf6b080-a3b0-11eb-954c-de85d7e2e61b.png)

Please use material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :) For example, the title should be placed in the action bar with a back button instead of the X.

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by ancutapopescu** [comment]
@aniri, I take this

**Comment by aniri** [comment]
closing this as it was implemented
