### ISSUE TITLE
Integrate backpack endpoints

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#54]
Complete backpack implementation. The UI is implemented, but the API is not linked. 

Please check swagger https://api.deurgenta.hostmysite.ro/swagger/index.html and complete functionality for:
- listing user backpacks
- adding new backpacks
- after the success response is received from the API, the backpack related info should also be stored locally in the db

**Comment by GabrielMajeri** [comment]
@aniri I want to work on this 🙋‍♂️
