### ISSUE TITLE
Integrate backpack items endpoints

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#55]
Complete backpack implementation. The UI is implemented, but the API is not linked.

Please check swagger https://api.deurgenta.hostmysite.ro/swagger/index.html and complete functionality for:

- list items from a backpack
- add / edit / delete backpack items
- after the success response is received from the API, the backpack items related info should also be stored locally in the db

**Comment by GabrielMajeri** [comment]
@aniri I want to work on this 🙋‍♂️
