### ISSUE TITLE
Integrate add group endpoint

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#56]
Complete add group implementation. The UI is implemented, but the API is not linked.

Please check swagger https://api.deurgenta.hostmysite.ro/swagger/index.html and complete functionality for:

- add new group
- - after the success response is received from the API, the group related info should also be stored locally in the db

**Comment by DeKaN** [comment]
@aniri Can I take this issue?

**Comment by aniri** [comment]
@DeKaN hey! :D sure! thanks

**Comment by DeKaN** [comment]
@aniri Can you share credentials for test account? Or should I register it myself?

**Comment by aniri** [comment]
@DeKaN it should work to create a new account :) if not, let me know :)
