### ISSUE TITLE
Implement groups list fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#58]
Design group list fragment. 

![image](https://user-images.githubusercontent.com/1358055/120065149-9696b600-c078-11eb-999e-48a1226d7b9a.png)

When opening the screen, all groups will be stacked. When clicking on a group name, the group members list should be retrieved from the api and expanded.

The numbers in parentheses after the group name are: the number of group members / maximum group members allowed (depends on https://github.com/code4romania/de-urgenta-backend/issues/68)

```
GET /groups/my

GET /group/{groupId}/members
```

An "add new group" button / link is missing from the UI. Please add one :)

The API calls for getting the group list and group members list are implemented. [Link to API in swagger](https://api.deurgenta.hostmysite.ro/swagger/index.html)

Please complete ui navigation between fragments. The groups list should open from the main menu & home screen.

Please define related colors and text & button styles in the corresponding values files.

Please use material design guidelines for android. The figma design is a bit ios oriented, it needs a bit of adapting for android :) For example, the title should be placed in the action bar with a back button instead of the X.

**Comment by Kardelio** [comment]
Hey @aniri 
This project looks awesome and like it is incredibly useful to lots of people! I would like to get involved if it is still possible and I would be interested in picking up this ticket, if that is ok?

Can i ask would it be ok to do this screen using Jetpack Compose for the UI (https://developer.android.com/jetpack/compose) as opposed to the XML approach for layouts? In this circumstance it would also mean not having to code up a Recyclerview adapter for the list of groups...

What do you think about that?

**Comment by aniri** [comment]
@Kardelio hey and thanks for your interest in our project! It would be great if you could pick up this ticket. But we'd like to keep the codebase consistent so please use the XML approach as for the rest of the layouts.

We'll keep Jetpack Compose in mind for our next app though, it really looks good!

**Comment by Kardelio** [comment]
@aniri ok gotcha!
Im happy to pick this one up then if thats ok with you?

**Comment by Kardelio** [comment]
Cool!
Can i ask a silly quesiton, I assume in order to get an auth token i need to create an account is that right?
OR is there a test account I can use to save me from creating an account? @aniri

**Comment by aniri** [comment]
You could create a new test account, yes :) 

Or you could use: `testing@example.com / testing`

**Comment by Kardelio** [comment]
@aniri thanks for that!
is there a link to the designs anywhere (like figma) so that I can set the right spacing etc... or should I just try to make it as close as i can to the screenshots above?
happy either way

**Comment by aniri** [comment]
@Kardelio we do have a figma https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530 . But as you see, the design is a bit ios oriented and needs some adjustments. It needs to be adapted a bit to respect material design guidelines for android. There are some existing styles already defined for the layout, you can use as many as possible from them :)

**Comment by Kardelio** [comment]
@aniri sorry to be a pain, im a little confused from where in the current app i need to navigate to this new group list screen?

I thought I would click `Create your group` and then created a group but then nothing happens it says success and thats it, am i supposed to navigate to the group list screen after this new group creation or do i need to add a new button on the `home` screen (you wrote in this issue `Please complete ui navigation between fragments. The groups list should open from the main menu & home screen.`) just want to make sure im doing the right thing, would you mind clearing this up a little bit for me? 

many thanks
K

**Comment by aniri** [comment]
@Kardelio 

Hey, I know the navigation in the app is a bit confusing and not 100% correctly implemented at the moment.

The first screen that shows up `Configure your account` is an onboarding part, this is linked to add a new group. For the moment we need to bypass it, with a small local hack: change from OnboardingActivity to MainActivity after login
```
fun onSuccessfulLogin() {
        val nextActivity = when (sharedPreferences.hasCompletedOnboarding()) {
            true -> MainActivity::class.java
            false -> MainActivity::class.java
        }
        loginLiveData.postValue(Result.Success(nextActivity))
    }
```

After this, you will reach the main (home) screen that has also a menu :) This is where the new screen with the groups list should be linked. To the main screen entry (corresponds to string `home_menu_item_group`) and menu entry (string `nav_menu_item_groups`).

I hope it's a bit more clear now! Btw, thanks for the heads up! I'll try and adjust the app a bit and include an easy way to bypass that onboarding part ;)

**Comment by Kardelio** [comment]
@aniri amazing thank you fully cleared up :) <3

**Comment by Kardelio** [comment]
@aniri couple of questions:
1. what dictates if the group (3 people icon) is red or grey (next to the group name)?
2. When the user clicks the chevron, I assume the chevron should point and face downwards as the members list expands, BUT at what point should i display the `edit group` grey text to the user instead?
3. Next to the group name there is 2 numbers in brackets, what do these numbers represent? In the data returned from `groups/my` i only get the `numberOfMembers` variable, should there be another one?

**Comment by aniri** [comment]
@Kardelio 

1. woooh! nice catch, this is not yet implemented in the backend app, I'll have to add an issue there :D But it wil be red if the logged in user is the admin of the group or not. You could leave a todo in to code for this check ;) 
1.1. The icons for members should be simpler, whatever you have the time to implement, as we might not have user images in the first version of the app. They can also be grey or red, based also on a flag that is not implemented yet in the backend. But you could use the `isGroupAdmin` flag for now.
2. The edit group shows only for the group the user is an admin of. Same rule as for 1. So also a todo :) 
3. Yes, there should be another number in the api response. You could use numberOfMembers for both numbers for now :)

Thanks!!

**Comment by Kardelio** [comment]
Hey @aniri apologies about how long it is taking me to complete this issue, I have not had any time for the past week or so to deal with it, but hopefully today ill have a little time to continue on it, however Im busy again after tomorrow for the next week, so I hope its ok and I hope there is no mega rush on this issue. But please rest assured I am working on it and I do intend to complete it, tbh i have most of the work done for it just need to get some UI done and thats mostly it.

Hope that all sounds ok!

**Comment by aniri** [comment]
hey @Kardelio don't worry! There's no rush, so whenever you have time it's perfect! It is a big issue, thanks a lot for picking it! :D

**Comment by aniri** [comment]
@Kardelio In the meantime, we also have some updates from the backend team 🚀  :

the reply for groups now contains the following:
```
{
    "id": "2f4a1bba-b726-4865-bd21-7f80c5156da2",
    "name": "Some name",
    "numberOfMembers": 4,
    "maxNumberOfMembers": 30, <- needed for displaying in the groups list
    "isCurrentUserAdmin": false <- needed for picking the color for the group icon & displaying the edit group text
 }
```

**Comment by aniri** [comment]
The new flag for members was also implemented, so the member image should be red if the flag `hasValidCertification` is true and grey if it is false.
