### ISSUE TITLE
Implement login fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#6]
Implement the login form screen as a fragment in the Login Activity.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113332535-f3504b80-9329-11eb-8112-fab767a53370.png)

to be added: login endpoint

After a successful login, the user should be redirected to the onboarding activity if onboarding was not completed and to the main activity otherwise.

User data (name, access token) should be saved in shared preferences.

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by ionutstoica14** [comment]
I'll start working on this
