### ISSUE TITLE
Replace `kotlin-android-extensions` Gradle plugin with View Binding and `kotlin-parcelize`

### ISSUE THREAD

**Issue by GabrielMajeri** [code4romania/de-urgenta-android#68]
Building the project in Android Studio produces warnings such as:

> The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

According to [this](https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html) Android Developers Blog post, the old `kotlin-android-extensions` will be removed in a Kotlin release during or after September 2021, so we should update our dependencies before then.

**Comment by lukstbit** [comment]
@GabrielMajeri Are you working on this?

**Comment by GabrielMajeri** [comment]
@lukstbit Nope, it's up for the grabs.

I initially thought I'd fix it in #69 but I've realized it's a bit too complicated for me :sweat_smile:

**Comment by lukstbit** [comment]
@GabrielMajeri Then I will make the change :)
