### ISSUE TITLE
Implement create account fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#7]
Implement the create account form screen as a fragment in the Login Activity.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113333742-7cb44d80-932b-11eb-9c92-249eb1bbc18e.png)

to be added: create account endpoint

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by ClaudiuBogdan** [comment]
🙋 I can take charge of this issue.

**Comment by aniri** [comment]
> 🙋 I can take charge of this issue.

🚀  awesome! It might be easier to start with this one https://github.com/code4romania/de-urgenta-android/issues/4 since they are related ;)

**Comment by ClaudiuBogdan** [comment]
@aniri I think we need to add a confirm password field to improve de UX.
I also added error messages on submit
