### ISSUE TITLE
Fix app navigation

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#76]
Navigation should work from onboading screen, main screen and menu.

Currently not all screens are reachable from all of the above options.

To be fixed in this issue -> navigation from side menu and home screen:

Onboarding screen:
![image](https://user-images.githubusercontent.com/1358055/138933013-e683a7f0-26a2-49d1-bb52-2211f4912d65.png)

Side menu:
![image](https://user-images.githubusercontent.com/1358055/138933946-d31927d9-7400-44c5-aa5d-1236819b7d93.png)
items to be fixed:
- emergency backpacks - should navigate to the same screen backpacks screen that is currently available only from onboarding

Home screen:
![image](https://user-images.githubusercontent.com/1358055/138933551-ee204389-8c5b-45b9-9f6e-8ce312639379.png)
items to be fixed:
- grupul de urgenta - should navigate to the same screen as from the emergency groups menu item
- rucsacul de urgenta - should navigate to the same screen backpacks screen that is currently available only from onboarding

**Comment by lukstbit** [comment]
Are you referring to on boarding screens  missing the drawer navigation?

**Comment by aniri** [comment]
Hey @lukstbit , I've been thinking, let's ignore the onboading related navigation for now. We'll get to that after all the related parts are implemented.

So this issue should cover making sure all the main menu items are linked to the implemented screens and also the links from the actual home screen are working. I don't think all screens are linked in both places.

**Comment by aniri** [comment]
@lukstbit Hey :) I checked the app and updated this issue to address only a couple of fixes.
