### ISSUE TITLE
Implement forgot password flow

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-android#9]
Implement the forgot password related screens.

Please define related colors and text & button styles in the corresponding values files.

![image](https://user-images.githubusercontent.com/1358055/113334855-de28ec00-932c-11eb-9e1a-fe74ac448eea.png)

to be added: reset password endpoint

After reseting the password, the user should be redirected to the login screen.

[Link to design in Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1466%3A530)

**Comment by grig-ian-theo** [comment]
@aniri, i take this

**Comment by aniri** [comment]
@grigore-theodorof hey! did you have time to work on this? :D

**Comment by andreiciubancanWD** [comment]
@aniri  I can take on this one
